# Generated by Django 5.2.6 on 2025-09-18 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('EXAM', 'Examen'), ('ASSIGNMENT', 'Tarea'), ('QUIZ', 'Quiz'), ('PROJECT', 'Proyecto'), ('FINAL', 'Examen Final')], default='EXAM', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Peso en el cálculo de nota final (1.0 = 100%)', max_digits=4)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='enrollment.enrollment')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['-graded_at'],
            },
        ),
    ]
