# Generated by Django 5.2.10 on 2026-02-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, db_index=True, default='', help_text='Documento Nacional de Identidad (8 dígitos). Puede estar vacío para registros antiguos.', max_length=8, verbose_name='DNI')),
                ('apellidos_nombres', models.CharField(db_index=True, help_text='Formato: "APELLIDO PATERNO MATERNO, NOMBRES"', max_length=250, verbose_name='Apellidos y Nombres')),
                ('grado_titulo', models.CharField(default='BACHILLER EN EDUCACIÓN', max_length=200, verbose_name='Grado / Título / Capacitación')),
                ('especialidad', models.CharField(max_length=150, verbose_name='Especialidad')),
                ('nivel', models.CharField(blank=True, default='', help_text='Ej: INICIAL, PRIMARIA, SECUNDARIA, PRIMARIA - SECUNDARIA', max_length=80, verbose_name='Nivel')),
                ('anio_ingreso', models.CharField(help_text='Ej: 2019, 2019-I, 2019-II', max_length=20, verbose_name='Año de Ingreso')),
                ('anio_egreso', models.CharField(help_text='Ej: 2023, 2023-I, 2023-II', max_length=20, verbose_name='Año de Egreso')),
                ('fecha_sustentacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Sustentación')),
                ('resolucion_acta', models.CharField(blank=True, default='', max_length=150, verbose_name='Resolución / Acta')),
                ('codigo_diploma', models.CharField(blank=True, default='', max_length=100, verbose_name='Código de Diploma')),
                ('director_general', models.CharField(blank=True, default='', max_length=200, verbose_name='Director General')),
                ('secretario_academico', models.CharField(blank=True, default='', max_length=200, verbose_name='Secretario Académico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Egresado',
                'verbose_name_plural': 'Egresados',
                'ordering': ['apellidos_nombres'],
                'indexes': [models.Index(fields=['dni'], name='grad_dni_idx'), models.Index(fields=['apellidos_nombres'], name='grad_nombre_idx'), models.Index(fields=['especialidad'], name='grad_esp_idx'), models.Index(fields=['anio_egreso'], name='grad_egreso_idx')],
            },
        ),
    ]
