# Generated by Django 5.2.10 on 2026-03-03 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0002_grado_titulo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='registro_pedagogico',
            field=models.CharField(blank=True, default='', help_text='Ej: R.P.N° 020280 -P-DREJ-H', max_length=100, verbose_name='Registro Pedagógico'),
        ),
        migrations.AlterField(
            model_name='gradotitulotype',
            name='diploma_label',
            field=models.CharField(default='TÍTULO', help_text='Texto que aparece como tipo en la constancia. Ej: "TÍTULO", "GRADO DE BACHILLER"', max_length=100, verbose_name='Etiqueta en diploma'),
        ),
        migrations.AlterField(
            model_name='gradotitulotype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gradotitulotype',
            name='template',
            field=models.CharField(help_text='Usa {especialidad} como placeholder. Ej: "PROFESOR(A) EN {especialidad}" → "PROFESOR(A) EN EDUCACIÓN INICIAL". Si no incluye {especialidad}, se usa el texto tal cual.', max_length=300, verbose_name='Plantilla de denominación'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='grado_titulo',
            field=models.CharField(blank=True, default='', help_text='Denominación completa. Se genera automáticamente desde el tipo + especialidad si está vacío.', max_length=200, verbose_name='Grado / Título (texto libre)'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='grado_titulo_type',
            field=models.ForeignKey(blank=True, help_text='Tipo de grado/título del catálogo. Si está vacío, se deriva de la especialidad.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='graduates.gradotitulotype', verbose_name='Tipo de Grado/Título'),
        ),
    ]
