# Generated by Django 5.2.10 on 2026-02-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_teacher_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_semesters', models.PositiveIntegerField(default=0)),
                ('vacancies', models.PositiveIntegerField(default=0)),
                ('degree_type', models.CharField(choices=[('BACHELOR', 'Bachiller'), ('TECHNICAL', 'Técnico'), ('PROFESSIONAL', 'Profesional')], default='BACHELOR', max_length=20)),
                ('modality', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('SEMIPRESENCIAL', 'Semipresencial')], default='PRESENCIAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
