# Generated by Django 5.2.10 on 2026-02-21 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisor',
            options={'ordering': ['full_name'], 'verbose_name': 'Asesor', 'verbose_name_plural': 'Asesores'},
        ),
        migrations.AlterModelOptions(
            name='budgetitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='deliverable',
            options={'ordering': ['due_date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='ethicsip',
            options={'verbose_name': 'Ética y PI', 'verbose_name_plural': 'Ética y PI'},
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Proyecto de investigación', 'verbose_name_plural': 'Proyectos de investigación'},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='proposalreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', 'title']},
        ),
        migrations.AlterModelOptions(
            name='researchline',
            options={'ordering': ['name'], 'verbose_name': 'Línea de investigación', 'verbose_name_plural': 'Líneas de investigación'},
        ),
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'ordering': ['start', 'end', 'id']},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='advisor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='orcid',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='ORCID'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='specialty',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='call',
            name='rubric_template',
            field=models.JSONField(blank=True, default=list, help_text='Rúbrica de evaluación: [{code, label, weight}, ...]'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='advisors',
            field=models.ManyToManyField(blank=True, related_name='projects_as_advisor', to='research.advisor', verbose_name='Co-asesores'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchline',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='researchline',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='full_name',
            field=models.CharField(max_length=160, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('SUBMITTED', 'Entregado'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_main', to='research.advisor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha fin'),
        ),
        migrations.AlterField(
            model_name='project',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='research.researchline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_REVIEW', 'En revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('RUNNING', 'En ejecución'), ('ON_HOLD', 'Suspendido'), ('FINISHED', 'Finalizado')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=220, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviada'), ('REVIEWED', 'Revisada'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('ARTICLE', 'Artículo'), ('BOOK', 'Libro'), ('CHAPTER', 'Capítulo'), ('CONFERENCE', 'Conferencia'), ('THESIS', 'Tesis'), ('OTHER', 'Otro')], max_length=40),
        ),
        migrations.AlterField(
            model_name='researchline',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Nombre'),
        ),
    ]
