# Generated by Django 5.2.6 on 2025-09-23 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('bank', models.CharField(blank=True, default='', max_length=80)),
                ('number', models.CharField(max_length=60, unique=True)),
                ('currency', models.CharField(choices=[('PEN', 'PEN'), ('USD', 'USD')], default='PEN', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('external_ref', models.CharField(blank=True, default='', max_length=80)),
                ('reconciled', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='finance.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('career_id', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.financeconcept')),
            ],
        ),
        migrations.CreateModel(
            name='AccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('STUDENT', 'STUDENT'), ('APPLICANT', 'APPLICANT')], max_length=20)),
                ('subject_id', models.IntegerField()),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(blank=True, default='', max_length=20)),
                ('ref', models.CharField(blank=True, default='', max_length=80)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.financeconcept')),
            ],
            options={
                'indexes': [models.Index(fields=['subject_type', 'subject_id', 'date'], name='finance_acc_subject_292c0d_idx')],
            },
        ),
    ]
