# Generated by Django 5.2.6 on 2025-11-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_concept_remove_incomeaggregate_concept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(default='SIN_CUENTA', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(default='PEN', max_length=8),
        ),
    ]
