# Generated by Django 6.0 on 2025-12-17 01:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_bankaccount_account_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(max_length=32, unique=True)),
                ('concept', models.CharField(choices=[('ENROLLMENT', 'Matrícula'), ('TUITION', 'Pensión'), ('CERTIFICATE', 'Constancia/Certificado'), ('PROCEDURE', 'Trámite'), ('ACADEMIC_SERVICES', 'Servicios Académicos'), ('OTHER', 'Otros')], default='OTHER', max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_document', models.CharField(max_length=11)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('CANCELLED', 'Anulado'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=16)),
                ('payment_method', models.CharField(blank=True, max_length=32, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=64, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
