# Generated by Django 6.0 on 2025-12-17 21:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_inventoryitem_inventorymovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_code', models.CharField(max_length=20, unique=True)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('bank_account', models.CharField(blank=True, max_length=64)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('BLACKLISTED', 'Lista Negra')], default='ACTIVE', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_number', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('justification', models.TextField()),
                ('required_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviado'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('CONVERTED_TO_PO', 'Convertido a OC')], default='DRAFT', max_length=20)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequirementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_of_measure', models.CharField(choices=[('UNIT', 'Unidad'), ('DOZEN', 'Docena'), ('KG', 'Kilogramo'), ('L', 'Litro'), ('M', 'Metro'), ('PKG', 'Paquete'), ('BOX', 'Caja')], default='UNIT', max_length=20)),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('technical_specifications', models.TextField(blank=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.purchaserequirement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
