# Generated by Django 6.0 on 2025-12-18 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_purchaseorder_purchaseorderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('document_number', models.CharField(max_length=16, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('position', models.CharField(max_length=120)),
                ('department', models.CharField(blank=True, max_length=120, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'Nombrado/Permanente'), ('TEMPORARY', 'Contratado'), ('CAS', 'CAS'), ('LOCACION', 'Locación de Servicios')], default='PERMANENT', max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('SUSPENDED', 'Suspendido'), ('RETIRED', 'Cesante/Jubilado'), ('TERMINATED', 'Cesado')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('break_minutes', models.IntegerField(default=0)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_attendance_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='finance.employee')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
