# Generated by Django 5.2.10 on 2026-02-07 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_applicationpreference'),
        ('catalogs', '0003_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpreference',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.career'),
        ),
        migrations.DeleteModel(
            name='Career',
        ),
    ]
