# Generated by Django 5.2.10 on 2026-02-16 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_alter_applicationpreference_career_delete_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='institution/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='evaluationscore',
            name='phase',
            field=models.CharField(default='WRITTEN', help_text='WRITTEN | INTERVIEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='admissioncall',
            name='period',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='career_name',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='evaluationscore',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='admission.application'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationscore',
            unique_together={('application', 'phase')},
        ),
    ]
