# Generated by Django 5.2.10 on 2026-02-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_institutionsetting_applicationdocument_original_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
