# Generated by Django 5.2.6 on 2025-09-20 04:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_career_options_alter_career_name_academicplan_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('number', models.PositiveIntegerField(default=1)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='courses.section')),
            ],
            options={
                'ordering': ['section_id', 'date', 'number'],
                'unique_together': {('section', 'number')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Justificado')], default='P', max_length=1)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='courses.sectionattendancesession')),
            ],
            options={
                'ordering': ['student_id'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
