# Generated by Django 4.2.13 on 2026-08-20 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0012_cv_item_textos_largos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADMINISTRATIVO', 'Administrativo'), ('LOCADOR', 'Locador 107 – MINEDU')], default='ADMINISTRATIVO', max_length=20)),
                ('cargo', models.CharField(blank=True, default='', help_text='Cargo según el Reglamento Institucional', max_length=160)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('document', models.CharField(blank=True, default='', max_length=30)),
                ('full_name', models.CharField(blank=True, default='', max_length=160)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('specialization', models.CharField(blank=True, default='', max_length=120)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('grado_academico', models.CharField(blank=True, choices=[('PROFESOR', 'Profesor (a)'), ('BACHILLER', 'Bachiller (a)'), ('LICENCIADO', 'Licenciado (a)'), ('MAGISTER', 'Magister (a)'), ('DOCTOR', 'Doctor (a)')], default='', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personal/photos/')),
                ('apellido_paterno', models.CharField(blank=True, default='', max_length=80)),
                ('apellido_materno', models.CharField(blank=True, default='', max_length=80)),
                ('nombres', models.CharField(blank=True, default='', max_length=120)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='', max_length=1)),
                ('telefono_fijo', models.CharField(blank=True, default='', max_length=30)),
                ('direccion', models.CharField(blank=True, default='', max_length=200)),
                ('region', models.CharField(blank=True, default='', max_length=80)),
                ('provincia', models.CharField(blank=True, default='', max_length=80)),
                ('distrito', models.CharField(blank=True, default='', max_length=80)),
                ('condicion_laboral', models.CharField(blank=True, choices=[('NOMBRADO', 'Nombrado (a)'), ('CONTRATADO', 'Contratado (a)'), ('LOCADOR', 'Locador (a) de servicios')], default='', max_length=20)),
                ('rd_nombramiento', models.CharField(blank=True, default='', max_length=120)),
                ('rd_fecha', models.DateField(blank=True, null=True)),
                ('orden_servicio', models.FileField(blank=True, null=True, upload_to='personal/orden_servicio/')),
                ('orden_servicio_numero', models.CharField(blank=True, default='', max_length=120)),
                ('orden_servicio_desde', models.DateField(blank=True, null=True)),
                ('orden_servicio_hasta', models.DateField(blank=True, null=True)),
                ('protocolo', models.FileField(blank=True, null=True, upload_to='personal/protocolo/')),
                ('plan_trabajo', models.FileField(blank=True, null=True, upload_to='personal/planes/')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_personal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['tipo', 'orden', 'apellido_paterno', 'full_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JefeLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('DIRECTOR_GENERAL', 'Director (a) General, en el caso de las EESP'), ('JEFE_UNIDAD_ACADEMICA', 'Jefe (a) de Unidad Académica'), ('JEFE_AREA_ADMINISTRACION', 'Jefe (a) del Área de Administración'), ('COORD_AREA_INICIAL', 'Coordinador (a) de Área Académica (Inicial)'), ('COORD_AREA_PRIMARIA', 'Coordinador (a) de Área Académica (Primaria)'), ('COORD_AREA_EDUC_FISICA', 'Coordinador (a) de Área Académica (Educación Física)'), ('COORD_PRACTICA_INVESTIGACION', 'Coordinador (a) de Área de Práctica Pre-Profesional e Investigación, en el caso de las EESP'), ('SECRETARIO_ACADEMICO', 'Secretario (a) Académico'), ('JEFE_INVESTIGACION', 'Jefe (a) de Unidad de Investigación e Innovación'), ('JEFE_FORMACION_CONTINUA', 'Jefe (a) de Unidad de Formación Continua'), ('JEFE_BIENESTAR', 'Jefe (a) de Unidad de Bienestar y Empleabilidad'), ('COORD_AREA_CALIDAD', 'Coordinador (a) de Área de Calidad'), ('JEFE_UNIDAD_POSGRADO', 'Jefe (a) de la Unidad de Posgrado, para el caso de las EES, según corresponda')], max_length=40, unique=True)),
                ('letra', models.CharField(blank=True, default='', max_length=2)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('resolucion', models.CharField(blank=True, default='', help_text='R.D. de designación en el cargo', max_length=160)),
                ('designado_desde', models.DateField(blank=True, null=True)),
                ('plan_trabajo', models.FileField(blank=True, null=True, upload_to='personal/planes/')),
                ('plan_trabajo_subido', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefaturas', to='catalogs.teacher')),
            ],
            options={
                'verbose_name': 'Jefe de línea',
                'verbose_name_plural': 'Jefes de línea',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PersonalCVItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('FORMACION', 'II. Formación profesional'), ('ESPECIALIZACION', 'III. Especialización y actualización'), ('EXPERIENCIA', 'IV. Experiencia laboral'), ('EVENTO', 'V.a Participación en eventos académicos'), ('PUBLICACION', 'V.b Publicaciones'), ('MERITO', 'VI. Méritos'), ('INVESTIGACION', 'VII. Investigación')], max_length=20)),
                ('subseccion', models.CharField(blank=True, choices=[('PREGRADO', 'Estudios de pregrado'), ('POSTGRADO', 'Estudios de postgrado'), ('SEGUNDA_ESP', 'Especialización o segunda especialización'), ('DIPLOMADO', 'Diplomado'), ('ACTIVIDAD', 'Actividad formativa'), ('IDIOMA', 'Idioma extranjero'), ('LENGUA', 'Lengua originaria'), ('TIC', 'Capacitación en TIC'), ('EXP_SUPERIOR', 'Docente en educación superior'), ('EXP_BASICA', 'Docente en educación básica / ETP'), ('EXP_CONTINUA', 'Formación docente en servicio / continua'), ('', '—')], default='', max_length=20)),
                ('institucion', models.CharField(blank=True, default='', max_length=500)),
                ('titulo', models.CharField(blank=True, default='', max_length=500)),
                ('detalle', models.TextField(blank=True, default='')),
                ('lugar', models.CharField(blank=True, default='', max_length=200)),
                ('duracion', models.CharField(blank=True, default='', max_length=120)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='personal/cv/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_items', to='personal.personal')),
            ],
            options={
                'ordering': ['seccion', 'subseccion', 'orden', 'fecha_inicio', 'id'],
                'indexes': [models.Index(fields=['personal', 'seccion'], name='personal_pe_persona_9d06b0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['tipo', 'activo'], name='personal_pe_tipo_e0ef9a_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['document'], name='personal_pe_documen_2d0a24_idx'),
        ),
        migrations.AddConstraint(
            model_name='personal',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='uniq_personal_user'),
        ),
    ]
