# Generated by Django 5.2.6 on 2025-09-23 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EXPORT_ENROLLMENTS', 'EXPORT_ENROLLMENTS'), ('EXPORT_GRADES', 'EXPORT_GRADES'), ('VALIDATION', 'VALIDATION'), ('SYNC_CATALOGS', 'SYNC_CATALOGS')], max_length=40)),
                ('cron', models.CharField(blank=True, default='', max_length=60)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MineduExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENROLLMENTS', 'ENROLLMENTS'), ('GRADES', 'GRADES')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('tries', models.PositiveIntegerField(default=0)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='minedu.integrationjob')),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('local_code', models.CharField(max_length=80)),
                ('remote_code', models.CharField(max_length=80)),
                ('label', models.CharField(blank=True, default='', max_length=160)),
            ],
            options={
                'unique_together': {('type', 'local_code')},
            },
        ),
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='minedu.jobrun')),
            ],
        ),
    ]
