# Generated by Django 5.2.10 on 2026-02-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minedu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mineduexportbatch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='mineduexportbatch',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mineduexportbatch',
            name='export_format',
            field=models.CharField(choices=[('XLSX', 'Excel'), ('CSV', 'CSV')], default='XLSX', max_length=10),
        ),
        migrations.AddField(
            model_name='mineduexportbatch',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='minedu/exports/'),
        ),
        migrations.AlterField(
            model_name='mineduexportbatch',
            name='data_type',
            field=models.CharField(choices=[('ENROLLMENT', 'Nómina de matrícula'), ('FICHA_MATRICULA', 'Ficha de matrícula'), ('GRADES', 'Acta consolidada de evaluación'), ('BOLETA', 'Boleta de notas'), ('STUDENTS', 'Ficha de estudiantes')], max_length=20),
        ),
        migrations.CreateModel(
            name='MineduCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('INSTITUTION', 'Institución (código modular)'), ('CAREER', 'Programa de estudios'), ('STUDY_PLAN', 'Plan de estudios')], max_length=20)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['type', 'code'],
                'unique_together': {('type', 'code')},
            },
        ),
    ]
