# Generated by Django 5.2.10 on 2026-02-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minedu', '0002_alter_mineduexportbatch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineducode',
            name='type',
            field=models.CharField(choices=[('INSTITUTION', 'Institución (código modular)'), ('CAREER', 'Programa de estudios'), ('STUDY_PLAN', 'Plan de estudios'), ('STUDENT', 'Estudiante (código matrícula SIA)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mineduexportbatch',
            name='data_type',
            field=models.CharField(choices=[('ENROLLMENT', 'Nómina de Matrícula'), ('FICHA', 'Ficha de Matrícula'), ('BOLETA', 'Boleta de Notas'), ('ACTA', 'Acta Consolidada de Evaluación'), ('REPORTE', 'Reporte de Información del Sistema (Kardex)'), ('REGISTRO_AUX', 'Registro Auxiliar de Evaluación'), ('CERTIFICADO', 'Certificado de Estudios')], max_length=20),
        ),
    ]
