# Generated by Django 5.2.6 on 2025-09-18 23:34

import django.core.validators
import django.db.models.deletion
import procedures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(default=procedures.models.default_tracking, help_text='Código de seguimiento del trámite (auto-generado).', max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('procedure_type', models.CharField(choices=[('CONSTANCIA_ESTUDIOS', 'Constancia de Estudios'), ('CERTIFICADO_NOTAS', 'Certificado de Notas'), ('DUPLICADO_CARNET', 'Duplicado de Carnet'), ('OTRO', 'Otro')], default='CONSTANCIA_ESTUDIOS', max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En Revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('DELIVERED', 'Entregado')], default='PENDING', max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='students.student')),
            ],
            options={
                'verbose_name': 'Procedure',
                'verbose_name_plural': 'Procedures',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tracking_code'], name='procedures__trackin_77dfe2_idx'), models.Index(fields=['status'], name='procedures__status_601ac0_idx'), models.Index(fields=['procedure_type'], name='procedures__procedu_7ef742_idx')],
            },
        ),
    ]
