# Generated by Django 5.2.10 on 2026-02-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_partes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='procedureevent',
            options={'ordering': ['-at']},
        ),
        migrations.AlterModelOptions(
            name='proceduretype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='office',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='office',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='canal_ingreso',
            field=models.CharField(blank=True, choices=[('VIRTUAL', 'Mesa de Partes Virtual'), ('PRESENCIAL', 'Mesa de Partes Presencial'), ('EMAIL', 'Correo Electrónico'), ('FAXSIMIL', 'Fax / Facsímil')], default='VIRTUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='procedure',
            name='urgency_level',
            field=models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='NORMAL', max_length=10),
        ),
    ]
