# Generated by Django 5.2.6 on 2025-09-26 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_partes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedurenotification',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='procedureroute',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='procedureroute',
            name='from_office',
        ),
        migrations.RemoveField(
            model_name='procedureroute',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='procedureroute',
            name='to_office',
        ),
        migrations.RemoveField(
            model_name='office',
            name='acronym',
        ),
        migrations.RemoveField(
            model_name='office',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='applicant_doc',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='code',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='office',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='type',
        ),
        migrations.RemoveField(
            model_name='procedurefile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='procedurefile',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='proceduretype',
            name='code',
        ),
        migrations.RemoveField(
            model_name='proceduretype',
            name='meta',
        ),
        migrations.AddField(
            model_name='procedure',
            name='applicant_document',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='procedure',
            name='current_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesa_partes.office'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='procedure_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='mesa_partes.proceduretype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='procedurefile',
            name='original_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='procedurefile',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proceduretype',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='proceduretype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proceduretype',
            name='processing_days',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='proceduretype',
            name='required_documents',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='applicant_name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('IN_REVIEW', 'IN_REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('COMPLETED', 'COMPLETED')], default='RECEIVED', max_length=16),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='tracking_code',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='procedurefile',
            name='doc_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='procedurefile',
            name='file',
            field=models.FileField(upload_to='procedures/'),
        ),
        migrations.AlterField(
            model_name='proceduretype',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='ProcedureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mesa_partes.procedure')),
            ],
        ),
        migrations.DeleteModel(
            name='ProcedureNote',
        ),
        migrations.DeleteModel(
            name='ProcedureNotification',
        ),
        migrations.DeleteModel(
            name='ProcedureRoute',
        ),
    ]
