# Generated by Django 6.0 on 2025-12-16 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='year',
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plan',
            name='semesters',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='start_year',
            field=models.PositiveSmallIntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='plancourse',
            name='type',
            field=models.CharField(choices=[('MANDATORY', 'Obligatorio'), ('ELECTIVE', 'Electivo')], default='MANDATORY', max_length=15),
        ),
        migrations.AddField(
            model_name='plancourse',
            name='weekly_hours',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='section',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='section',
            name='period',
            field=models.CharField(default='2025-I', max_length=20),
        ),
        migrations.AlterField(
            model_name='courseprereq',
            name='prerequisite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='academic.plancourse'),
        ),
        migrations.AlterUniqueTogether(
            name='courseprereq',
            unique_together={('plan_course', 'prerequisite')},
        ),
        migrations.AlterUniqueTogether(
            name='plancourse',
            unique_together={('plan', 'course')},
        ),
    ]
