# Generated by Django 5.2.10 on 2026-02-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_institutionsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='end_year',
            field=models.PositiveSmallIntegerField(default=2025),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('career', 'start_year', 'end_year'), name='uniq_plan_by_career_year_range'),
        ),
    ]
