# Generated by Django 6.0 on 2026-01-06 04:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_remove_plan_year_plan_description_plan_semesters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='SectionGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.JSONField(default=dict)),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grades_bundle', to='academic.section')),
            ],
        ),
    ]
