# Generated by Django 5.2.10 on 2026-02-05 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_plan_end_year_plan_uniq_plan_by_career_year_range'),
        ('students', '0003_student_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicperiod',
            name='enrollment_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='enrollment_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='max_credits_normal',
            field=models.PositiveSmallIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='max_credits_third_attempt',
            field=models.PositiveSmallIntegerField(default=11),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='min_credits_normal',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='passing_grade',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=5),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=12)),
                ('total_credits', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveSmallIntegerField(default=0)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academic.enrollment')),
                ('plan_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.plancourse')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academic.section')),
            ],
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'period'], name='academic_en_student_40b606_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['period', 'status'], name='academic_en_period_6f6e56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentitem',
            unique_together={('enrollment', 'plan_course')},
        ),
    ]
