# Generated by Django 5.2.10 on 2026-02-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_academicperiod_enrollment_end_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plancourse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='plancourse',
            name='display_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='plancourse',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddConstraint(
            model_name='plancourse',
            constraint=models.UniqueConstraint(condition=models.Q(('display_code', ''), _negated=True), fields=('plan', 'display_code'), name='uniq_plan_display_code'),
        ),
    ]
