# Generated by Django 5.2.10 on 2026-02-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_plancourse_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
