# Generated by Django 5.2.10 on 2026-02-07 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_plan_is_deleted'),
        ('catalogs', '0003_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='catalogs.career'),
        ),
        migrations.DeleteModel(
            name='Career',
        ),
    ]
