# Generated by Django 5.2.10 on 2026-02-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_plan_career_delete_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancourse',
            name='credits',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddConstraint(
            model_name='plancourse',
            constraint=models.UniqueConstraint(fields=('plan', 'course'), name='uniq_plan_course'),
        ),
    ]
