# Generated by Django 5.2.10 on 2026-02-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_fix_plan_soft_delete_default'),
        ('catalogs', '0004_importjob_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plan',
            name='uniq_plan_by_career_year_range',
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('career', 'start_year', 'end_year'), name='uniq_plan_by_career_year_range'),
        ),
    ]
