# Generated by Django 5.2.10 on 2026-02-13 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_remove_plan_uniq_plan_by_career_year_range_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='academicgraderecord',
            name='academic_ac_student_8fe1cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='academicgraderecord',
            name='academic_ac_course__40a6ad_idx',
        ),
        migrations.AlterUniqueTogether(
            name='academicgraderecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='academicgraderecord',
            name='plan_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_records', to='academic.plancourse'),
        ),
    ]
