# Generated by Django 5.2.10 on 2026-02-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_remove_academicgraderecord_academic_ac_student_8fe1cd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprocess',
            name='kind',
            field=models.CharField(max_length=60),
        ),
    ]
