# Generated by Django 5.2.10 on 2026-02-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_alter_academicprocess_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicperiod',
            name='extemporary_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='extemporary_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='extemporary_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto de recargo por matrícula extemporánea (soles)', max_digits=8),
        ),
    ]
