# Generated by Django 5.2.10 on 2026-02-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_academicperiod_extemporary_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicperiod',
            options={'ordering': ['-code']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code']},
        ),
        migrations.AlterField(
            model_name='academicperiod',
            name='extemporary_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Recargo por matrícula extemporánea (soles)', max_digits=8),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['period'], name='academic_se_period_210e9c_idx'),
        ),
    ]
