# Generated by Django 5.2.10 on 2026-03-06 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_alter_academicperiod_options_alter_course_options_and_more'),
        ('students', '0003_student_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_tag', models.CharField(blank=True, default='', max_length=30)),
                ('surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('channel', models.CharField(choices=[('PAGALO', 'Págalo.pe'), ('CAJERO_MULTIRED', 'Cajero Multired'), ('AGENCIA_BN', 'Agencia Banco de la Nación')], max_length=20)),
                ('operation_code', models.CharField(blank=True, default='', max_length=60)),
                ('voucher', models.FileField(upload_to='enrollment_vouchers/')),
                ('voucher_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_enrollment_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_payments', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['period', 'status'], name='academic_en_period_000366_idx')],
                'unique_together': {('student', 'period')},
            },
        ),
    ]
